from scrapy import Field
from scrapy.item import Item

class WineItem(Item):
    name = Field()
    url = Field()
    price = Field()
    vintage = Field()
    # msrp = Field()
    # brand = Field()
    region = Field()
    varietals = Field()
    # foods = Field()
    wine_type = Field()
    # body = Field()
    # tannin = Field()
    image = Field()
    # characteristics = Field()
    description = Field()
    # purpose = Field()
    sku = Field()
    bottle_size = Field()
    qoh = Field()
    # highlights = Field()
    # single_product_url = Field()
    alcohol_pct = Field()
    # drink_from = Field()
    # drink_to = Field()
    # acidity = Field()
    # discount_pct = Field()
    # flaw = Field()
    reviews = Field()
